---
- name: Check if SSL Certificate already exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ iam_domain }}/fullchain.pem"
  register: cert_stat

- name: Get the first SSL cert (Only if it doesn't exist)
  ansible.builtin.command:
    cmd: >
      certbot certonly --standalone
      -d {{ iam_domain }}
      --email {{ certbot_email_cloudlabs }}
      --agree-tos
      --non-interactive
  when: not cert_stat.stat.exists

- name: Generate HAProxy .pem file (Overwrite mode)
  ansible.builtin.shell:
    cmd: >
      cat /etc/letsencrypt/live/{{ iam_domain }}/fullchain.pem
      /etc/letsencrypt/live/{{ iam_domain }}/privkey.pem
      > {{ haproxy_pem_path }}

- name: Cron Job certbot renew (Runs twice a day safely)
  ansible.builtin.cron:
    name: "Renew {{ iam_domain }} TLS cert"
    minute: "0"
    hour: "0,12"
    job: "{{ renew_cert_script_path }}"