[nimbus]
nimbus.cloudlabs.ufscar ansible_host=10.0.36.1

[incus]
inc1-cirrus.cloudlabs.ufscar ansible_host=192.168.200.85
inc2-cirrus.cloudlabs.ufscar ansible_host=192.168.200.88
inc3-cirrus.cloudlabs.ufscar ansible_host=
inc4-stratus.cloudlabs.ufscar ansible_host=
inc5-stratus.cloudlabs.ufscar ansible_host=
inc6-stratus.cloudlabs.ufscar ansible_host=

[freeipa]
freeipa.cloudlabs.ufscar ansible_host=172.18.1.23

[auth-sidecar]
keycloak.cloudlabs.ufscar ansible_host=

[gateway-mgc]
gateway-mgc.cloudlabs.ufscar ansible_host=

[nimbus-cluster:child]
nimbus
incus

[auth-cluster:child]
freeipa
auth-sidecar

[gateways-ufscar-mgc:child]
nimbus
gateway-mgc
