[incus]
inc1 192.168.200.83
inc2 192.168.200.84
inc3 192.168.200.85
inc4
inc5
inc6

[nimbus]
nimbus 10.0.36.1

[cluster-nimbus:child]
incus
nimbus

[auth]
keycloak
freeipa
gateway-mgc-vpn

[servers:child]
cluster-nimbus
auth
