#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy

# 1. Instalação dos pacotes necessários
- name: Packages Installation
  ansible.builtin.import_tasks: install-packages.yml

# 2. Estruturação dos arquivos na máquina alvo
- name: Copy files in LB machine
  ansible.builtin.import_tasks: copy-archives.yml

# 3. Configuração certificados Let's Encrypt
- name: TLS Configuration
  ansible.builtin.include_tasks: configure-tls.yml
  loop: "{{ incus_clusters }}"

# 4. cron job
- name: Cron Job certbot renew (Runs twice a day)
  ansible.builtin.cron:
    name: "Renew TLS cert"
    minute: "0"
    hour: "0,12"
    job: "{{ renew_cert_script_path }}"

# 5. Docker compose up -d
- name: Docker Compose deploy
  ansible.builtin.import_tasks: deploy-lb.yml