name: Update repo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connects via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/repos/Auth-repo

            EXPECTED_URL="https://github.com/cloudlabs-ufscar/Auth-repo.git"
            CURRENT_URL=$(git remote get-url origin)

            if [ "$CURRENT_URL" != "$EXPECTED_URL" ]; then
              # here we check if the repo in the server is pointing to the correct repo before we run scripts from it
              echo "[!] Remote URL ($CURRENT_URL) does not match expected repository! (Did we change the community/repo name?)"
              exit 1
            fi

            git fetch origin main
            git reset --hard origin/main

            echo "[*] repo updated in the server"

            
